rclone mount eco-menorcaon-com:eco-menorcaon-com/shuttlespain/INBOX /var/www/vhosts/eco.menorcaon.com/shuttlespain.eco.menorcaon.com/documents/verifactu/INBOX \
  --allow-other \
  --allow-non-empty \
  --umask 0000 \
  --daemon \
  --log-file=/var/log/rclone-verifactu.log \
  --log-level DEBUG
