rclone mount eco-menorcaon-com:eco-menorcaon-com/shuttlespain/INBOX \
  /var/www/vhosts/eco.menorcaon.com/shuttlespain.eco.menorcaon.com/documents/verifactu/INBOX \
  --allow-other \
  --umask 0000 \
  --vfs-cache-mode full \
  --vfs-cache-max-size 1G \
  --vfs-cache-max-age 24h \
  --daemon \
  --log-file=/var/log/rclone-verifactu.log \
  --log-level INFO


  rclone mount eco-menorcaon-com:eco-menorcaon-com/shuttlespain/OUTBOX \
  /var/www/vhosts/eco.menorcaon.com/shuttlespain.eco.menorcaon.com/documents/verifactu/OUTBOX \
  --allow-other \
  --umask 0000 \
  --vfs-cache-mode full \
  --vfs-cache-max-size 1G \
  --vfs-cache-max-age 24h \
  --daemon \
  --log-file=/var/log/rclone-verifactu.log \
  --log-level INFO